[[search_dirs]]
path = "~/repos/work"
depth = 1

[[search_dirs]]
path = "~/repos/"
depth = 1

[[search_dirs]]
path = "~"
depth = 1

# Network drive notes (only appears when mounted)
[[search_dirs]]
path = "/mnt/mbospace/foconnell/notes"
depth = 1
