#!/bin/bash

set -e

sudo apt install -y btop polybar picom ripgrep libusb-1.0-0-dev

# - Keymapp ----
if ! command -v keymapp &> /dev/null; then
    echo "keymapp is not installed. Installing..."
    # Download the tar.gz file
    curl -L https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz -o keymapp-latest.tar.gz
    tar -xzf keymapp-latest.tar.gz
    sudo mv keymapp /usr/bin/keymapp
    sudo chmod +x /usr/bin/keymapp
    rm keymapp-latest.tar.gz
else
    echo "keymapp is already installed. Skipping installation."
fi


if ! command -v fzf &> /dev/null; then
    echo "fzf is not installed. Installing..."
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
else
    echo "fzf is already installed. Skipping installation."
fi

# - Kitty ----
if ! command -v kitty &> /dev/null; then
    echo "kitty terminal emulator is not installed. Installing..."
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n installer=nightly
    sudo ln -s ~/.local/kitty.app/bin/kitty /usr/local/bin/
    cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
    cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
    sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
    sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
else
    echo "kitty terminal emulator is already installed. Skipping installation."
fi

# - Node ----
if ! command -v kitty &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

    NODE_MAJOR=21
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

    sudo apt-get update
    sudo apt-get install nodejs -y

else
    echo "Node runtime is already installed. Skipping installation."
fi

# - TPM ----
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    # If not, clone the tpm repository
    echo "Cloning tmux plugin manager (tpm)..."
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
else
    echo "tmux plugin manager (tpm) already exists. Skipping clone."
fi

chmod +x $HOME/.local/bin/*
chmod +x $HOME/.local/opt/*
