#!/bin/bash

# Install firefox-nightly via apt so it can autoupdate
sudo install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

# Lets be good programmers here
FINGERPRINT=$(gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | awk '/pub/{getline; gsub(/^ +| +$/,""); print $0}')
EXPECTED_FINGERPRINT="35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3"

if [[ "$FINGERPRINT" == *"$EXPECTED_FINGERPRINT"* ]]; then
    echo "Fingerprint verification succeeded."
else
    echo "Fingerprint verification failed."
    exit 1
fi

echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

sudo apt update && sudo apt install -y firefox-nightly
echo "Firefox Nightly installation completed."

